apiVersion: apps/v1
kind: Deployment
metadata:
  name: clients-api
  labels:
    app: clients-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clients-api
  template:
    metadata:
      labels:
        app: clients-api
    spec:
      containers:
      - name: clients
        image: netecdev/clients:0.1.0
        # Asegúrate de que la aplicación dentro de la imagen
        # realmente escuche en el puerto 8888.
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: clients-api-service
  labels:
    app: clients-api
spec:
  selector:
    app: clients-api
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP
      name: http
  # NodePort para poder acceder en Minikube desde tu host
  type: NodePort
